# Generated by Django 5.2.5 on 2025-09-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fristname',
            new_name='firstname',
        ),
    ]
