# Generated by Django 5.2.6 on 2025-09-06 03:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_address_user_created_at_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='adrev',
        ),
        migrations.AddField(
            model_name='department',
            name='abrev',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='department',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
