# Generated by Django 5.2.6 on 2025-09-06 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='id_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='authentication.country'),
        ),
    ]
