# Generated by Django 5.2.6 on 2025-10-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_country_status'),
    ]

    operations = [
       
    ]
